//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM_RS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIM_RS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilih Kriteria.
        /// </summary>
        internal static string daftarHakAkses_Pencarian_Pilih_Kriteria {
            get {
                return ResourceManager.GetString("daftarHakAkses_Pencarian_Pilih_Kriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER SUDAH PUNYA MENU TERSEBUT
        ///SILAHKAN PILIH MENU YG LAIN.
        /// </summary>
        internal static string DaftarHakAkses_PvSimpanData_ {
            get {
                return ResourceManager.GetString("DaftarHakAkses_PvSimpanData_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM TIDAK DITEMUKAN.
        /// </summary>
        internal static string daftarHakAkses_txtNamaAppLama_Leave_PROGRAM_TIDAK_DITEMUKAN {
            get {
                return ResourceManager.GetString("daftarHakAkses_txtNamaAppLama_Leave_PROGRAM_TIDAK_DITEMUKAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERHATIAN.
        /// </summary>
        internal static string daftarHakAkses_txtNamaMenu_Leave_PERHATIAN {
            get {
                return ResourceManager.GetString("daftarHakAkses_txtNamaMenu_Leave_PERHATIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETUGAS TIDAK DITEMUKAN.
        /// </summary>
        internal static string daftarHakAkses_txtNamaMenu_Leave_PETUGAS_TIDAK_DITEMUKAN {
            get {
                return ResourceManager.GetString("daftarHakAkses_txtNamaMenu_Leave_PETUGAS_TIDAK_DITEMUKAN", resourceCulture);
            }
        }
    }
}
